### ISSUE TITLE
Facebook: Support "Links" and "Photos"

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#13]
Ted Hesson could not add this FB Permalink post to his article through the Facebook Post Element: 
https://www.facebook.com/permalink.php?story_fbid=615251015278265&id=380505205419515

We also need to do images: https://www.facebook.com/RichardBranson/photos/a.10151193550160872.451061.31325960871/10151193550380872/?type=3&theater

**Comment by davisshaver** [comment]
Ran into https://core.trac.wordpress.org/ticket/11311 (which seems related but different than https://core.trac.wordpress.org/ticket/15694). The ampersand in the shortcode URL attribute gets converted to `&amp;` by kses, which breaks the shortcode on the frontend. This bug doesn't show on the admin because of permissions for unfiltered_html.

Here's how this bug is solved with the [embed] shortcode: https://github.com/WordPress/WordPress/blob/2f3e567f44e7bc335b6795713ae970b4f37117cd/wp-includes/class-wp-embed.php#L152

I'm going to solve in the same manner for now.

**Comment by davisshaver** [comment]
Hm. That worked. But I'm seeing some strange behavior.

- Shortcode works as expected when logged-in
- Doesn't work when logged in, and it looks like the & is being caught by https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L316

**Comment by danielbachhuber** [comment]
:ship:
