### ISSUE TITLE
Some questions about direction of Shortcake Bakery

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/shortcake-bakery#17]
I've spent some time working on the bakery and would like to discuss a few points.

I've been looking at our `fusion-theme` repository and thinking about which shortcodes we could open source. I've done a few basic ones (PDFs, Rap Genius, Infogram) and thinking about how this repository will likely ending up being mostly 3rd party embeds (e.g. those we didn't design ourselves), because the 1st-party shortcodes tend to be theme/business specific.

Since it's mostly 3rd party embeds, it makes me wonder why they aren't more helpful in making it happen. Well, some are, with oEmbed, and one way I'm thinking about Shortcake and Shortcake Bakery is "shims for oEmbed". Especially since [oEmbed discovery is disabled by default](https://wordpress.org/plugins/enable-oembed-discovery/), I feel Shortcake fills the missing space between WordPress and 3rd party sites.

This value add is also what could make the repository hard to maintain. The reliance on regex makes the whole thing rather brittle. How long will Facebook have a photo URL structure that looks like this, for instance, `https://www.facebook.com/RichardBranson/photos/a.10151193550160872.451061.31325960871/10151193550380872/?type=3&theater`. Could be 5 years. Could be 5 weeks. 

When considered this way, the plugin starts to sound like [Embedly](https://wordpress.org/plugins/embedly/). We are writing shims to make wild URL's (and even the embed codes themseves) transform into structured/oembed-ish macros. This direction feels a bit different than where Shortcake is headed, which is more of a developer than consumer facing plugin.

**Comment by davisshaver** [comment]
@goldenapples @danielbachhuber let me know your thoughts on this, or we can also chat in Slack about it.

**Comment by danielbachhuber** [comment]
> let me know your thoughts on this

I'm not 100% clear what the question is. Can you clarify?

In my mind, Shortcake Bakery is this:

* A collection of useful shortcodes, written in a common pattern. Implementers get all shortcodes by default, but they can easily disable some or add their own.
* Each shortcode has: UI, (optional) reversal for transforming embed code into the shortcode, test coverage to limit breakage.
* Shortcodes are ideal because they're a WordPress standard for storing macros within blob text. Shortcodes give us easy programmatic control over embed output.

We could eventually offer oEmbed-esque experience #5 for shortcodes that are essentially just a URL reference.

> This value add is also what could make the repository hard to maintain. The reliance on regex makes the whole thing rather brittle. How long will Facebook have a photo URL structure that looks like this, for instance, https://www.facebook.com/RichardBranson/photos/a.10151193550160872.451061.31325960871/10151193550380872/?type=3&theater. Could be 5 years. Could be 5 weeks.

You could say the same thing about oEmbed. In our case, largely because we're starting out with good test coverage (as opposed to, say, Jetpack), we could easily accommodate this change in the future.

**Comment by goldenapples** [comment]
I'm just getting started thinking about this project so I'm not sure I have all the context for it, but I'll try and jump in here as well.

> one way I'm thinking about Shortcake and Shortcake Bakery is "shims for oEmbed"

Hmm. Just because most of the Fusion shortcodes we're open-sourcing are basically wrappers around third-party embeds doesn't necessarily mean that the plugin should center that type of shortcode. It seems to me like the "embed"-type shortcodes are a key part of the plugin, but maybe they should be somehow organized separately.  

As I see it, there are two primary reasons people would use/extend this plugin: markup-based shortcodes and embed-based ones. Methods like `reversal` are only relevant to the embed shortcodes. If you were building a shortcode to display a Google map or custom blockquote markup, defining a `reversal` method likely wouldn't be feasible.

So I'm wondering if it makes sense to abstract out different types of shortcode classes with classes like `Shortcake_Bakery\Shortcodes\Embed` that extend `Shortcake_Bakery\Shortcodes\Shortcode` and provide some sugar for use-case specific functionality?

**Comment by davisshaver** [comment]
@goldenapples @danielbachhuber I noticed that in Hong's Q3 goals, longform will be coming into the WordPress environment. I agree that Shortcake is a good tool for managing this type of "Markup" based macro, and that reversal wouldn't be applicable for the vast majority. 

Do we need to split the classes now? Not sure I see much advantage, as `reversal` is inert unless defined within the shortcode, and it's unclear what the sugar we'd be providing to markup shortcodes entails.

I think for now maybe we should just keep moving ahead with this distinction in mind, and as we start building more markup macros (think: Our abstractions for the Paul Ford Code/Snowfall style article) we can look to identify some use-case specific functionality in that build.

**Comment by danielbachhuber** [comment]
> Do we need to split the classes now? Not sure I see much advantage, as reversal is inert unless defined within the shortcode, and it's unclear what the sugar we'd be providing to markup shortcodes entails.

I don't see a pressing need. It's not clear what problem it would solve.
