### ISSUE TITLE
Add shortcode for Heading 1-6

### ISSUE THREAD

**Issue by jimmyandrade** [fusioneng/shortcake-bakery#22]
The following code is theme-agnostic.
https://github.com/jimmyandrade/shortcake-bakery/blob/master/inc/shortcodes/class-heading.php

**Comment by davisshaver** [comment]
@jimmyandrade The code looks reasonable, would you just mind expanding on the use-case for a heading shortcode? At Fusion we have similar editorial concepts like ledes and pullquotes, but these were built as shortcodes because of the need for custom markup. One downside in UX is that a heading shortcode wouldn't be editable inline.

**Comment by jimmyandrade** [comment]
The usefulness of a particular shortcode for titles, in this case, is that they can have a link to themselves: that would be good in terms of SEO. In addition, using a specific function of WordPress, each heading would have its own HTML ID attribute. This could be useful for navigation on posts or pages with big content: we could put a "Back to the top." before every heading. Also, we could include automatic generation of an index according to the headings used.

**Comment by danielbachhuber** [comment]
It seems like all of these use cases can be accommodated by adding a filter on `the_content`. I don't think heading is a unique-enough shortcode that it makes sense to include in Shortcake Bakery.
