### ISSUE TITLE
Fix visual consistency of icons

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#95]
![image](https://cloud.githubusercontent.com/assets/36432/10102135/a3ab99bc-6351-11e5-8ec9-6c95e96f7124.png)

They all should be `#444` and equivalent size.

**Comment by danielbachhuber** [comment]
@FStop can you pick this up over the next couple of days? dashicons would be our baseline for style and color. Here are the fixes I see us needing to make:

* [ ] Infogram - color and positioning (size is probably fine)
* [ ] Instagram - size
* [ ] Rap Genius - positioning, maybe size slightly
* [ ] Scribd - color, maybe size slightly
* [ ] Twitter - size
* [ ] Vimeo - size
* [ ] Vine - size
* [ ] YouTube - size

**Comment by FStop** [comment]
@danielbachhuber I'd be glad to.

**Comment by FStop** [comment]
It looks like 64 x 64 is good dimensions for square-ish images, and 100 x 64 or so will work for the wider images.

**Comment by FStop** [comment]
@danielbachhuber how do you feel about some tweaking to the CSS for these items in Shortcode UI? 

The vertical centering seems a little weird to me for both images and dashicons. The icon container height is set with line-height to the full height of the container (150px) but it should probably be the height minus the height of the title.

Image icons also have width="100" height="100" attributes regardless of dimensions. I don't think those attributes are even necessary here.

I can put together a PR with some quick improvements if you like.

<img width="188" alt="screenshot 2015-09-29 11 00 34" src="https://cloud.githubusercontent.com/assets/1437322/10170239/935d38e0-6699-11e5-9404-76f799cec485.png">
<img width="223" alt="screenshot 2015-09-29 10 59 41" src="https://cloud.githubusercontent.com/assets/1437322/10170240/935e7fa2-6699-11e5-9bd3-204ac447bb75.png">

**Comment by FStop** [comment]
The height and width attributes added to the images is overriding the image size. I resized the Instagram icon to be 64 x 64, but it's still rendering at 100 x 100:

<img width="641" alt="screenshot 2015-09-29 11 48 54" src="https://cloud.githubusercontent.com/assets/1437322/10171539/4024c3da-66a0-11e5-993b-a069e7d5f550.png">

With `height` and `width` attributes removed in devtools the image is at its natural size:
<img width="640" alt="screenshot 2015-09-29 11 51 08" src="https://cloud.githubusercontent.com/assets/1437322/10171585/7e7ec982-66a0-11e5-94a1-3fd05a6229e2.png">

There's still a `padding-top: 10px` added inline, which is kinda strange.

**Comment by FStop** [comment]
OK I can see where the `width` and `height` attributes are coming from now. They're [hard coded in the shortcode classes](https://github.com/fusioneng/shortcake-bakery/blob/f6eae2d42be5ad0a80988fd20563ff791fb82ff6/inc/shortcodes/class-instagram.php#L10). I'd like to get rid of these attributes, so that the images can be properly sized and aligned.

**Comment by danielbachhuber** [comment]
> I'd like to get rid of these attributes, so that the images can be properly sized and aligned.

Fine by me :) They were a lazy hack in the first place.

**Comment by FStop** [comment]
Cool. This is what things look like without the size attributes:
<img width="1438" alt="screenshot 2015-09-29 15 32 48" src="https://cloud.githubusercontent.com/assets/1437322/10177378/7d9b2e9c-66bf-11e5-9f4c-8bc7b832e169.png">

A little crazy, but it's good because we can see what images need to be resized.

I'll add the following to the list:

- [ ] Playbuzz - size, transparent instead of white in the middle
- [ ] Silk - size
- [ ] Sparkinfluence - transparency
- [ ] Videoo - size

**Comment by danielbachhuber** [comment]
Looks much better now. Thanks @FStop
